### ISSUE TITLE
Allow separate asset/pokemon icons

### ISSUE THREAD

**Issue by clburlison** [versx/MapJS#104]
After PR #100 the icons are now a dictionary. 
```json
    "icons": {
        "Default": {
            "path": "/img/",
            "gymAnchorY": 0.917,
            "pokestopAnchorY": 0.896
        }
    },
```

Since this change got pushed I'm currently going to recommend a new pokemon key that would point to "/img/pokemon" by default. That would allow us to change this to shuffle, shiny shuffle, pokemon home, derby, etc all while still maintaining the UI assets for the map. 

design decisions
1. we could include a check such that if the Pokemon key is missing it uses the "path" like master and appends the /pokemon subdirectory. This could go way more advanced to allowing each sub-element to be overwritten? I currently don't really need that but adding it now might make things easier in the future if someone else does want that?

2. Does it make sense to rename "path" to something like "basepath"?

**Comment by Mygod** [comment]
Symlink? 😅

**Comment by Mygod** [comment]
Also you can simply handle the fallback with express.js. It doesn't make sense to let the client to the fallback.

**Comment by Mygod** [comment]
Ok with the new patch the client can do fallback now, but this only brings up more issue. If pack A has female pokemon and pack B does not, should it fallback to pack A or just display male asset in pack B? If it's a costume female, and pack A only has female and pack B only has costume, which fallback should you pick? Personally I would give this a wontfix and let the server admin decide all these details.

**Comment by versx** [comment]
Closing this after the recent icon standard update #141
