### ISSUE TITLE
Nests filter broken, trying to remove any pokemon removes all

### ISSUE THREAD

**Issue by AtakuHydra** [versx/MapJS#125]
Title, here is a short gif:
![5d228b49cc1450eb896132a8d17b3c36](https://user-images.githubusercontent.com/22157510/91937469-f6198e00-ecbf-11ea-97a0-271cc9eaf60f.gif)

**Comment by versx** [comment]
Anything show in your browser console?

**Comment by AtakuHydra** [comment]
Nothing, in particular, I have been seeing this though:
![image](https://user-images.githubusercontent.com/22157510/92018729-863cef00-ed23-11ea-8996-87629c913dd4.png)

**Comment by bschultz** [comment]
Should be fixen with PR #127

**Comment by AtakuHydra** [comment]
confirmed
