### ISSUE TITLE
Stardust cost filter broken

### ISSUE THREAD

**Issue by AtakuHydra** [versx/MapJS#126]
Changing the cost filter to anything other then 0, removes all stardust quests instead of filtering.

Example: 

https://gyazo.com/a5836652ac9bc6f8a62c9359408d14c4

**Comment by AtakuHydra** [comment]
No console logs

**Comment by versx** [comment]
Weird, works fine for me (set to 500) 
![image](https://user-images.githubusercontent.com/1327440/92020948-d27d3480-ed0d-11ea-93af-5843a17e3fbd.png)

**Comment by versx** [comment]
What version of MySQL/MariaDB?

**Comment by AtakuHydra** [comment]
5.7.30-0ubuntu0.16.04.1

**Comment by versx** [comment]
Need v8

**Comment by AtakuHydra** [comment]
will update and close if resolved

**Comment by AtakuHydra** [comment]
Can confirm updating to 8.0.21 solved the issue.

**Comment by Mygod** [comment]
Interesting. Is it because `<>`?

**Comment by versx** [comment]
> Interesting. Is it because `<>`?

It's because we use `JSON_VALUE` to get the value form the json in the column which is only supported in MySQL 8. RDM uses `JSON_PARSE` twice although I had issues with it and used `JSON_VALUE` instead.
