### ISSUE TITLE
"Unexpected end of JSON input" when turning on nests and pokemon with global filters.

### ISSUE THREAD

**Issue by AtakuHydra** [versx/MapJS#128]
![image](https://user-images.githubusercontent.com/22157510/92039823-bbf1d000-ed43-11ea-9d70-500dbbede476.png)

Steps:
Turn on nests, Turn on pokemon with global filters "(S0-1 & A15 & D15 & L0-20) | L35 | 90-100"

**Comment by Mygod** [comment]
Looks like incorrect configuration on mapjs instead.

**Comment by versx** [comment]
Closing this since I'm not able to reproduce the error. If this is still an issue feel free to re-open it.
