### ISSUE TITLE
PVP Rank Medals Assigned Incorrectly

### ISSUE THREAD

**Issue by sketchysocks** [versx/MapJS#154]
I tried to track down the issue myself but I was having trouble pinpointing it. All of these have "Rank 1" data for Ultra, with Mareep also having "Rank 1" data for Great so there seems to be a few edge cases that are making it past the minimum CP filter, even though the "Rank 1" info isn't listed in the pop up, only in the db. 

![pvp-mareep](https://user-images.githubusercontent.com/58572875/92412412-cb916000-f119-11ea-94ce-8dcca9eaba80.PNG)
![pvp-murkrow](https://user-images.githubusercontent.com/58572875/92412413-cc29f680-f119-11ea-8866-5e54bed92925.PNG)
![pvp-omanyte](https://user-images.githubusercontent.com/58572875/92412414-cc29f680-f119-11ea-8e3a-fed8e5c38360.PNG)

**Comment by Mygod** [comment]
Probably due to the inconsistent filter cp > 1400/2400.

**Comment by sketchysocks** [comment]
I tried changing these values, as they seem like typos that have somehow been missed:
https://github.com/versx/MapJS/blob/da2ce6b8c6e9ff720997f4ec001158709ae87c8b/src/views/index-js.mustache#L2235-L2237

But didn't seem to fix the issue.

**Comment by versx** [comment]
I've been meaning to fix that, thanks for reminding me.
