### ISSUE TITLE
Bug: quest_43

### ISSUE THREAD

**Issue by clburlison** [versx/MapJS#188]
Text for one of the next mega energy quests needs to be added

![B33726EB-6D24-48BC-B49E-2ECB423CBDCA](https://user-images.githubusercontent.com/2831320/93027598-967e8500-f5d3-11ea-861b-94f1a094dc32.png)

![95E7E262-E5B0-493E-90FF-25DE4DA75468](https://user-images.githubusercontent.com/2831320/93027627-c3cb3300-f5d3-11ea-8980-8b1aa23090b9.jpeg)

**Comment by bschultz** [comment]
Did you update pogo-translations? `npm update pogo-translations`

The text is updated there. After update you have to run `npm create-locales`

**Comment by clburlison** [comment]
Thank you @bschultz that was it.
