### ISSUE TITLE
feat: Grunt rewards

### ISSUE THREAD

**Issue by clburlison** [versx/MapJS#70]
Super excessive nice to have but being able to show the possible grunt rewards. Highly recommend stealing the json format from pmsf, a few projects have already done so, then it's easier for community to update in the future.

![8BC64673-B258-4256-AF8F-6975B06E303F](https://user-images.githubusercontent.com/2831320/90949383-4c0f4b80-e40d-11ea-812f-3d32d55910f3.jpeg)

![C3DD35CA-5C2A-4181-849F-D53FA9255532](https://user-images.githubusercontent.com/2831320/90949386-516c9600-e40d-11ea-8857-e8440a2b32c9.jpeg)

https://github.com/pmsf/PMSF/blob/master/static/data/grunttype.json

**Comment by Mygod** [comment]
We could make the scanners scan the lineup in the future, maybe even skip scanning if the past lineup history gives us 95% confidence that the lineup is fixed. Admin can change the rocket lineups last update time if the lineup has changed (or we might even be able to detect it automatically).
